In [35]:
# Assignment 3
# TASK 1
# Quest: Write a function to compute 5/0 and use try/except to catch the exceptions

def compute():
    a=0
    try:
        a=5/0
        print(a)
    except Exception as e:
        print(e)
compute()

division by zero


In [19]:
# Assignment 3
# TASK 1
# Quest: Implement a Python program to generate all sentences where subject is in ["Americans",
        #"Indians"] and verb is in ["Play", "watch"] and the object is in ["Baseball","cricket"].

def AddLists(x,y,z):
    return (x + " " + y + " " + z)

subjects=["Americans","Indians"]
verbs=["play","watch"]
objects=["Baseball","Cricket"]

c=''
for x in subjects:
    for y in verbs:
        for z in objects:
            c=AddLists(x,y,z)
            print(c)


#c=list((i + " " + j + " " + k)for k in objects for j in verbs for i in subjects)
#print(c)

Americans play Baseball
Americans play Cricket
Americans watch Baseball
Americans watch Cricket
Indians play Baseball
Indians play Cricket
Indians watch Baseball
Indians watch Cricket


In [69]:
# Assignment 3
# TASK 2
# Quest 1: Write a function so that the columns of the output matrix are powers of the input vector.
# N - i - 1

import numpy as np

N=3
c=[]
x=np.array([2,3,4,5])
for i in list(range(3)):
    print(x**(N-i-1))


[ 4  9 16 25]
[2 3 4 5]
[1 1 1 1]
